overrides:
  is-core-module: npm:@nolyfill/is-core-module@^1.0.39
  isarray: npm:@nolyfill/isarray@^1.0.44
  safe-buffer: npm:@nolyfill/safe-buffer@^1.0.44
  "@nuxt/kit": 3.19.3
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  simple-git-hooks: true
  unrs-resolver: true
minimumReleaseAge: 0
